"""integracao entre Token e User

Revision ID: 59948fec6f98
Revises: 7898d7666acd
Create Date: 2025-03-06 18:20:57.615249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59948fec6f98'
down_revision = '7898d7666acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_user_id', sa.Integer()))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_tokens__user_id_users'), 'users', ['_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tokens__user_id_users'), type_='foreignkey')
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('_user_id')

    # ### end Alembic commands ###
