"""altera a tabela tokens

Revision ID: 611a751dd764
Revises: 59948fec6f98
Create Date: 2025-03-16 15:22:25.379832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611a751dd764'
down_revision = '59948fec6f98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.alter_column('_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.alter_column('_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
