"""adiciona freq cardiaca e elevacao

Revision ID: 7223cffaae69
Revises: e34e67ba2e4f
Create Date: 2025-03-23 15:59:40.027833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7223cffaae69'
down_revision = 'e34e67ba2e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fc_max', sa.Double(), nullable=True))
        batch_op.add_column(sa.Column('fc_avg', sa.Double(), nullable=True))
        batch_op.add_column(sa.Column('elevation', sa.Double(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('elevation')
        batch_op.drop_column('fc_avg')
        batch_op.drop_column('fc_max')

    # ### end Alembic commands ###
