"""cria tabela users

Revision ID: 7898d7666acd
Revises: 908155a17b1a
Create Date: 2025-03-04 23:30:09.271962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7898d7666acd'
down_revision = '908155a17b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strava_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('lastname', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('strava_id', name=op.f('uq_users_strava_id'))
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_activities_strava_id'), ['strava_id'])
        batch_op.create_foreign_key(batch_op.f('fk_activities_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_activities_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_activities_strava_id'), type_='unique')
        batch_op.drop_column('user_id')

    op.drop_table('users')
    # ### end Alembic commands ###
