"""migracao inicial

Revision ID: c73b078064b0
Revises: 
Create Date: 2025-03-02 15:56:02.622436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73b078064b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strava_id', sa.String(length=16), nullable=False),
    sa.Column('last_update_desc', sa.String(length=32), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_update_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['activity_states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('last_update_desc'),
    sa.UniqueConstraint('strava_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activities')
    op.drop_table('activity_states')
    # ### end Alembic commands ###
