"""adiciona a coluna type na tabela activities

Revision ID: e34e67ba2e4f
Revises: 611a751dd764
Create Date: 2025-03-16 15:25:29.514702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e34e67ba2e4f'
down_revision = '611a751dd764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
